# Generated by Django 5.2.18 on 2026-10-08 07:50

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_pending(apps, schema_editor):
    """Pending rows queued before this field existed: their last update is the submission."""
    RecruiterProfile = apps.get_model("recruiters", "RecruiterProfile")
    RecruiterProfile.objects.filter(verification_status="pending", submitted_at__isnull=True).update(
        submitted_at=F("updated_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiterprofile",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_pending, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="recruiterprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("verification_status", "pending"), _negated=True),
                    ("submitted_at__isnull", False),
                    _connector="OR",
                ),
                name="recruiter_pending_has_submitted_at",
            ),
        ),
    ]
