# Generated by Django 5.2.17 on 2026-10-01 10:14

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', max_length=12)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.media')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TalentCraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.craft')),
                ('talent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.talenttype')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_crafts', to='talent.talentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('craft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.craft')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('unavailable', 'Unavailable')], max_length=12)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to='talent.talentprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='talentprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['genres'], name='talent_genres_gin'),
        ),
        migrations.AddIndex(
            model_name='talentprofile',
            index=models.Index(fields=['is_published', 'city'], name='talent_pub_city_idx'),
        ),
        migrations.AddIndex(
            model_name='talentprofile',
            index=models.Index(fields=['date_of_birth'], name='talent_dob_idx'),
        ),
        migrations.AddConstraint(
            model_name='talentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('years_experience__isnull', True), ('years_experience__lte', 80), _connector='OR'), name='talent_years_experience_sane'),
        ),
        migrations.AddIndex(
            model_name='talentcraft',
            index=models.Index(fields=['craft', 'is_primary'], name='talentcraft_craft_idx'),
        ),
        migrations.AddConstraint(
            model_name='talentcraft',
            constraint=models.UniqueConstraint(fields=('talent', 'craft'), name='talentcraft_unique'),
        ),
        migrations.AddConstraint(
            model_name='talentcraft',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('talent',), name='talentcraft_one_primary'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(condition=models.Q(('end_year__isnull', True), ('end_year__gte', models.F('start_year')), _connector='OR'), name='experience_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(condition=models.Q(('start_year__gte', 1900), ('start_year__lte', 2100)), name='experience_start_year_sane'),
        ),
        migrations.AddIndex(
            model_name='availabilityoverride',
            index=models.Index(fields=['talent', 'date'], name='availability_talent_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityoverride',
            constraint=models.UniqueConstraint(fields=('talent', 'date'), name='availability_unique_day'),
        ),
        migrations.AddConstraint(
            model_name='availabilityoverride',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['tentative', 'unavailable'])), name='availability_not_default'),
        ),
    ]
