# Generated by Django 5.2.17 on 2026-10-01 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('purpose', models.CharField(choices=[('gallery', 'Gallery'), ('avatar', 'Avatar')], default='gallery', max_length=10)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('pdf', 'PDF'), ('link', 'Link')], max_length=10)),
                ('status', models.CharField(choices=[('pending_upload', 'Pending upload'), ('processing', 'Processing'), ('ready', 'Ready'), ('rejected', 'Rejected')], default='pending_upload', max_length=16)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('thumbnail_key', models.CharField(blank=True, max_length=512)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('craft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.craft')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'media',
            },
        ),
        migrations.CreateModel(
            name='MediaLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='media_library.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['owner', 'status'], name='media_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['craft', 'status'], name='media_craft_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'link'), _negated=True), ('external_url__gt', ''), _connector='OR'), name='media_link_has_url'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose', 'avatar'), _negated=True), ('kind', 'image'), _connector='OR'), name='media_avatar_is_image'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), ('kind', 'link'), ('storage_key__gt', ''), _connector='OR'), name='media_ready_has_storage_key'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__isnull', True), ('size_bytes__gte', 0), _connector='OR'), name='media_size_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medialike',
            constraint=models.UniqueConstraint(fields=('user', 'media'), name='medialike_unique'),
        ),
    ]
